version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: labsassigment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello@post123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:hello%40post123@db/labsassigment
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
